version: "3"

services:
    postgres:
        container_name: riscos_db
        image: postgres:alpine
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: riscos_db
        ports:
            - 5532:5432
        volumes:
            - riscos_db:/var/lib/postgresql/data
            - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

volumes:
    riscos_db:
        name: riscos_db
