sonar.projectKey=ufc.npi.gestaoriscos
sonar.projectName=Gestao de Riscos
sonar.projectVersion=0.0.1

sonar.sources=back-gestao-riscos/src/main,front-gestao-riscos/src

sonar.java.binaries=back-gestao-riscos/target/classes

sonar.sourceEncoding=UTF-8
